server:
  port: ${SERVER_PORT:8073}
spring:
  profiles:
    active: local
  application:
    name: spring-cloud-consumer

  cloud:
    loadbalancer:
      ribbon:
        enable: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
