server:
  port: ${SERVER_PORT:8071}
spring:
  profiles:
    active: local
  application:
    name: spring-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
      config:
        server-addr: ${REGISTER_HOST:localhost}:${REGISTER_PORT:8848}
        file-extension: yml
        import-check:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
